### ISSUE TITLE
Returns as #VALUE!

### ISSUE THREAD

**Issue by willgrnr** [prikhi/libreoffice-binance-api#1]
See image.

![image](https://user-images.githubusercontent.com/9218348/59223930-247eeb00-8b9b-11e9-892d-107c73af96eb.png)

**Comment by prikhi** [comment]
I couldn't reproduce this, what OS, verison, and libreoffice version are you using?

**Comment by rumpelstielzchen-dec** [comment]
Hi, have the same problem. OS: Ubuntu 18.04.3 LTS, LibreOffice 6.3.1.2

**Comment by willgrnr** [comment]
>@prikhi I couldn't reproduce this, what OS, verison, and libreoffice version are you using?

Windows 10 x64, Libre Office 10 v6.2.2.2 (x64), problem persists with v6.3.3.2 (x64).

**Comment by kulak** [comment]
I might know what's wrong with it.  ADAUSD is invalid ticker for `https://api.binance.com/api/v1/ticker/24hr?symbol=ADAUSD` URL, but it works with `https://api.binance.us/api/v1/ticker/24hr?symbol=ADAUSD` URL.

Base URL in source code uses `api.binance.com` and thus does not work in US.

**Comment by prikhi** [comment]
Cool, fixed & released new version, lemme know if it works.

**Comment by kulak** [comment]
it works like a charm
